### ISSUE TITLE
Facebook login problem

### ISSUE THREAD

**Issue by max4all** [ueberauth/ueberauth_facebook#20]
I keep getting `The parameter app_id is required` response. 

`https://www.facebook.com/dialog/oauth?auth_type=&client_id=&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Ffacebook%2Fcallback&response_type=code&scope=email&state=`

**Comment by aphillipo** [comment]
Simple fix is to get an AppId and Secret from facebook:

https://developers.facebook.com/ -> My Apps in the right hand corner -> Add a new app -> Website -> Follow the instructions.

It can be a bit of a pain to setup because facebook seem to be trying to force you to use their Javascript SDK.

You'll then need to add config in config.exs:

``` elixir
config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: "SET YOUR APP ID HERE",
  client_secret: "SET YOUR CLIENT SECRET HERE"
```

Of course you probably shouldn't commit this to git and should manage your secrets more carefully.  E.g. config/dev.secrets.exs

**Comment by doomspork** [comment]
Hi @max4all, have you setup your config as @aphillipo laid out?
