### ISSUE TITLE
Cannot authenticate with FB

### ISSUE THREAD

**Issue by ehayun** [ueberauth/ueberauth_facebook#63]
I am getting this
```
[info] TLS :client: In state :wait_cert_cr at ssl_handshake.erl:1899 generated CLIENT ALERT: Fatal - Unknown CA

%Ueberauth.Failure{
  errors: [
    %Ueberauth.Failure.Error{
      message: "The code has been used or has expired",
      message_key: "invalid_code"
    }
  ],
  provider: :facebook,
  strategy: Ueberauth.Strategy.Facebook
}
```
any idea?

**Comment by ianjaku** [comment]
Make sure you're on the newest version of ueberauth_facebook.
`mix deps.update ueberauth_facebook`

Otherwise if you're using phoenix turn on debug_errors by adding `debug_errors: true` to your Endpoint config.
This will give you the real error because the one you posted is a rather generic error in the code.

**Comment by arjan** [comment]
#65 has an update that allows you to update to ueberauth 0.7

**Comment by yordis** [comment]
I published a new version, please reopen the issue if it still happening
